version: '3.9'

services:

  java_app:           #Este es nuestro backend
    container_name: java_app  #nombre del contenedor
    image: java-app:1.0.0
    build: .
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mysql://java_db:3306/ContaduriaVehiculos
      - spring.datasource.username=root
      - spring.datasource.password=1413odgc
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: mysql:latest         #Es la imagen de la bd, la da docker, es por defecto
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1413odgc
      MYSQL_DATABASE: ContaduriaVehiculos

